variable "region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "kms_key_account" {}
variable "kms_key_id" {}
variable "asm_secret_account" {}
variable "asm_secret_name" {}
variable "ch_cloud" {}
variable "ch_environment" {}
variable "ch_team" {}
variable "ch_project" {}
variable "ch_user" {}